---
- name: handler_start_sshd
  systemd:
    name: "sshd.service"
    state: started
    daemon_reload: yes

- name: handler_stop_sshd
  systemd:
    name: "sshd.service"
    state: stopped
    daemon_reload: yes

- name: handler_restart_sshd
  systemd:
    name: "sshd.service"
    state: restarted
    daemon_reload: yes

- name: handler_reload_sshd
  systemd:
    name: "sshd.service"
    state: reloaded
    daemon_reload: yes

- name: handler_enable_sshd
  systemd:
    name: "sshd.service"
    enabled: yes
    daemon_reload: yes
