
---
- name: handler_start_unattended-upgrades
  systemd:
    name: "unattended-upgrades.service"
    state: started
    daemon_reload: yes

- name: handler_stop_unattended-upgrades
  systemd:
    name: "unattended-upgrades.service"
    state: stopped
    daemon_reload: yes

- name: handler_restart_unattended-upgrades
  systemd:
    name: "unattended-upgrades.service"
    state: restarted
    daemon_reload: yes

- name: handler_enable_unattended-upgrades
  systemd:
    name: "unattended-upgrades.service"
    enabled: yes
    daemon_reload: yes
