---
- name: install web server (apache2)
  package:
    name: "apache2"
    state: present
    update_cache: yes
    cache_valid_time: "{{ CACHE_VALID_TIME }}"
  notify:
    - handler_enable_apache2
  tags:
    - apache2
    - package
    - install_package

- name: install apache2 mods
  apache2_module:
    name: "{{ item }}"
    state: "{{ mod_state }}"
  with_items:
    - "proxy_ajp"
    - "rewrite"
  notify:
    - handler_reload_apache2
  tags:
    - apache2
    - apache2_module
    - install_mod

- include: "create_user_and_group.yml"
  when: username != "www-data"

- name: create directory "{{ domain_name }}/" in "/var/www/", set owner to "root", set group to "root" and set directory mode to "0755"
  file:
    path: "/var/www/{{ domain_name }}/"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - apache2
    - file
    - create_directory

- name: create directories ".ssh/", "cgi-bin/", "conf/apache2/", "conf/ssl/", "htdocs/", "log/", "private/", "tmp/" in "/var/www/{{ domain_name }}/", set owner to "{{ username }}", set group to "{{ username }}" and set directory mode to "0755"
  file:
    path: "/var/www/{{ domain_name }}/{{ sub_directory }}/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  with_items:
    - ".ssh"
    - "cgi-bin"
    - "conf/apache2"
    - "conf/ssl"
    - "htdocs"
    - "log"
    - "private"
    - "tmp"
  loop_control:
      loop_var: "sub_directory"
  tags:
    - apache2
    - file
    - create_directory

- name: create file "authorized_keys" in directory "/var/www/{{ domain_name }}/.ssh/", set owner to "{{ username }}", set group to "{{ username }}" and set file mode to "0600"
  file:
    path: "/var/www/{{ domain_name }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
  changed_when: false

- name: replace line "Subsystem\tsftp\t/usr/lib/sftp-server" with "Subsystem sftp internal-sftp" in file "/etc/ssh/sshd_config" and reload sshd configuration files
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: "Subsystem\tsftp\t/usr/lib/openssh/sftp-server"
    replace: "Subsystem sftp internal-sftp"
  notify:
    - handler_reload_sshd

- name: insert lines in file "/etc/ssh/sshd_config" for sftp chroot for directory "/var/www/{{ domain_name }}/" and reload sshd configuration files
  blockinfile:
    path: "/etc/ssh/sshd_config"
    block: |
      Match User "{{ username }}"
          ChrootDirectory %h
          ForceCommand internal-sftp
    marker: "# {mark} sftp chroot: /var/www/{{ username }}"
  notify:
    - handler_reload_sshd

- name: replace line "#PasswordAuthentication yes" with "PasswordAuthentication yes" in file "/etc/ssh/sshd_config" and reload sshd configuration files
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: "#PasswordAuthentication yes"
    replace: "PasswordAuthentication yes"
  notify:
    - handler_reload_sshd
